apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: springboot
  name: springboot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: springboot
  strategy: {}
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
      - image: sammakaorz/springboot:1.0.0-20
        name: springboot
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
