apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot
  name: springboot
  namespace: default
spec:
  ports:
  - nodePort: 30296
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: springboot
  type: NodePort
